/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaGrafica;

import capaLogicaNegocios.AppProyecto;
import capaLogicaNegocios.Cuenta;
import capaLogicaNegocios.Producto;
import capaPersistencia.ArchivadorUsuario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmReporte extends javax.swing.JFrame {

    /**
     * Creates new form FrmReporte
     */
    public FrmReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);

        jButton1.setText("Productos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Total a pagar Salonero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton4.setText("Total monto de las cuentas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 429, 71));

        jLblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAtencionC.png"))); // NOI18N
        getContentPane().add(jLblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JOptionPane.showMessageDialog(null, Producto.listadoProducto(),"Productos: ",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(FrmReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String ID=JOptionPane.showInputDialog(
        null, 
        "Ingrese el ID del salonero a buscar", 
        "Buscar pago de saloneros", 
        JOptionPane.WARNING_MESSAGE);
        
          
        
        
        
        if(ArchivadorUsuario.buscarUsuario(ID)!=null){
            try {
                //JOptionPane.showMessageDialog(null, "Total propina: "+Cuenta.sumaPropina(ID));
                ArrayList<Cuenta> arrayCuentaT=Cuenta.listadoCuentas();
                double propina=0;
                for (Cuenta cuentaT : arrayCuentaT) {
                    if(cuentaT.getSalonero().getCedula().equalsIgnoreCase(ID)){
                    propina+=cuentaT.impuestoServicio();
                }
                    
                }
                JOptionPane.showMessageDialog(null, "Total propina: "+propina);
            } catch (Exception ex) {
                Logger.getLogger(FrmReporte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No existe usuario con la cédula: "+ID,"Error al buscar el usuario",JOptionPane.ERROR_MESSAGE);
        }
    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double totalDecuentas=0;
        try {
            ArrayList<Cuenta> arrayCuentaT=Cuenta.listadoCuentas();
            for (Cuenta cuenta : arrayCuentaT) {

                totalDecuentas+=cuenta.total();
            }
        } catch (Exception ex) {
            Logger.getLogger(FrmReporte.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Total de las cuentas: "+totalDecuentas+ " colones");
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLblFondo;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
